// src/lib/mockup-data.ts
import { CategoryInfo, MockupTemplate, MockupCategory } from '@/types';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'books',
    name: 'Books & Covers',
    description: '3D hardcovers, paperbacks and multi-book stacks',
    icon: 'BookOpen',
    color: '#f97316',
    gradient: 'from-orange-500 to-amber-600',
  },
  {
    id: 'boxes',
    name: 'Software Boxes',
    description: '3D product boxes for software, courses & digital products',
    icon: 'Package',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-600',
  },
  {
    id: 'phones',
    name: 'Mobile Devices',
    description: 'Latest smartphones in various angles and orientations',
    icon: 'Smartphone',
    color: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-600',
  },
  {
    id: 'tablets',
    name: 'Tablets',
    description: 'Modern iPad-style tablets in portrait and landscape',
    icon: 'Tablet',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'laptops',
    name: 'Laptops',
    description: 'Sleek MacBook-style laptops with customizable screen display',
    icon: 'Laptop',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'desktops',
    name: 'Computers & Desktops',
    description: 'Desktop monitors from iMac to ultrawide screens',
    icon: 'Monitor',
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
  },
  {
    id: 'browsers',
    name: 'Browser Windows',
    description: 'Clean Chrome/Safari-style frames to showcase web UI/UX',
    icon: 'Globe',
    color: '#f59e0b',
    gradient: 'from-yellow-500 to-orange-500',
  },
  {
    id: 'websites',
    name: 'Website Windows',
    description: 'Full-page and perspective website UI mockups',
    icon: 'Layout',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
  },
  {
    id: 'multi-device',
    name: 'Multi-Device Bundles',
    description: 'Full scenes combining Phone + Tablet + Laptop + Desktop',
    icon: 'Layers',
    color: '#14b8a6',
    gradient: 'from-teal-500 to-cyan-600',
  },
];

export const TEMPLATES: MockupTemplate[] = [
  // ── BOOKS ──────────────────────────────────────────────────────────
  {
    id: 'book-hardcover-front',
    name: 'Hardcover Front',
    category: 'books',
    description: 'Classic 3D hardcover book viewed from the front',
    previewBg: '#1a0a00',
    aspectRatio: '3/4',
    clipZone: { x: 12, y: 8, width: 70, height: 84 },
  },
  {
    id: 'book-hardcover-angle',
    name: 'Hardcover Angled',
    category: 'books',
    description: '3D hardcover book with perspective angle and spine visible',
    previewBg: '#0f0a1a',
    aspectRatio: '3/4',
    clipZone: { x: 8, y: 8, width: 60, height: 84 },
  },
  {
    id: 'book-paperback',
    name: 'Paperback',
    category: 'books',
    description: 'Softcover paperback book front view',
    previewBg: '#001a0f',
    aspectRatio: '3/4',
    clipZone: { x: 10, y: 5, width: 72, height: 90 },
  },
  {
    id: 'book-stack',
    name: 'Stack of Books',
    category: 'books',
    description: 'Three stacked books — great for course bundles',
    previewBg: '#1a1500',
    aspectRatio: '4/3',
    clipZone: { x: 15, y: 5, width: 65, height: 55 },
  },
  // ── BOXES ──────────────────────────────────────────────────────────
  {
    id: 'box-front',
    name: 'Product Box Front',
    category: 'boxes',
    description: 'Clean 3D product box facing forward',
    previewBg: '#0a001a',
    aspectRatio: '1/1',
    clipZone: { x: 10, y: 8, width: 60, height: 72 },
  },
  {
    id: 'box-angled',
    name: 'Angled Box',
    category: 'boxes',
    description: 'Product box in 3/4 perspective view with top and side visible',
    previewBg: '#1a0010',
    aspectRatio: '1/1',
    clipZone: { x: 8, y: 12, width: 52, height: 65 },
  },
  {
    id: 'box-double',
    name: 'Double Box Stack',
    category: 'boxes',
    description: 'Two product boxes stacked — ideal for bundle promotions',
    previewBg: '#00001a',
    aspectRatio: '4/3',
    clipZone: { x: 12, y: 6, width: 55, height: 60 },
  },
  // ── PHONES ─────────────────────────────────────────────────────────
  {
    id: 'phone-portrait',
    name: 'Phone Portrait',
    category: 'phones',
    description: 'Modern smartphone in portrait mode (flat)',
    previewBg: '#001a1a',
    aspectRatio: '9/19',
    clipZone: { x: 5, y: 10, width: 90, height: 80 },
  },
  {
    id: 'phone-angled',
    name: 'Phone Angled',
    category: 'phones',
    description: 'Smartphone tilted at an angle with subtle shadow',
    previewBg: '#0a0a1a',
    aspectRatio: '9/19',
    clipZone: { x: 8, y: 12, width: 84, height: 76 },
  },
  {
    id: 'phone-floating',
    name: 'Phone Floating',
    category: 'phones',
    description: 'Floating smartphone with glow shadow underneath',
    previewBg: '#000a1a',
    aspectRatio: '9/19',
    clipZone: { x: 6, y: 11, width: 88, height: 78 },
  },
  // ── TABLETS ────────────────────────────────────────────────────────
  {
    id: 'tablet-portrait',
    name: 'Tablet Portrait',
    category: 'tablets',
    description: 'iPad-style tablet in portrait orientation',
    previewBg: '#001a10',
    aspectRatio: '3/4',
    clipZone: { x: 8, y: 12, width: 84, height: 76 },
  },
  {
    id: 'tablet-landscape',
    name: 'Tablet Landscape',
    category: 'tablets',
    description: 'iPad-style tablet in landscape orientation',
    previewBg: '#0a1a00',
    aspectRatio: '4/3',
    clipZone: { x: 12, y: 8, width: 76, height: 84 },
  },
  {
    id: 'tablet-angled',
    name: 'Tablet Angled',
    category: 'tablets',
    description: 'Tablet at a slight 3D perspective angle',
    previewBg: '#1a0a10',
    aspectRatio: '3/4',
    clipZone: { x: 10, y: 10, width: 76, height: 72 },
  },
  // ── LAPTOPS ────────────────────────────────────────────────────────
  {
    id: 'laptop-front',
    name: 'Laptop Open',
    category: 'laptops',
    description: 'MacBook-style laptop open, screen facing forward',
    previewBg: '#00001a',
    aspectRatio: '16/9',
    clipZone: { x: 12, y: 6, width: 76, height: 73 },
  },
  {
    id: 'laptop-angled',
    name: 'Laptop Side Angle',
    category: 'laptops',
    description: 'Laptop in 3/4 perspective showing keyboard and screen',
    previewBg: '#0a001a',
    aspectRatio: '16/9',
    clipZone: { x: 15, y: 5, width: 65, height: 62 },
  },
  {
    id: 'laptop-topdown',
    name: 'Top-Down View',
    category: 'laptops',
    description: 'Overhead view of laptop showing screen and keyboard',
    previewBg: '#1a1a00',
    aspectRatio: '4/3',
    clipZone: { x: 10, y: 5, width: 80, height: 55 },
  },
  // ── DESKTOPS ───────────────────────────────────────────────────────
  {
    id: 'desktop-imac',
    name: 'iMac Style',
    category: 'desktops',
    description: 'All-in-one iMac style desktop monitor',
    previewBg: '#001a1a',
    aspectRatio: '16/9',
    clipZone: { x: 10, y: 6, width: 80, height: 72 },
  },
  {
    id: 'desktop-ultrawide',
    name: 'Ultrawide Monitor',
    category: 'desktops',
    description: '21:9 ultrawide monitor for wide-format screenshots',
    previewBg: '#1a001a',
    aspectRatio: '21/9',
    clipZone: { x: 5, y: 8, width: 90, height: 74 },
  },
  {
    id: 'desktop-tilted',
    name: 'Monitor Tilted',
    category: 'desktops',
    description: 'Desktop monitor in slight 3D tilt for dynamic look',
    previewBg: '#0a1a1a',
    aspectRatio: '16/9',
    clipZone: { x: 12, y: 8, width: 74, height: 68 },
  },
  // ── BROWSERS ───────────────────────────────────────────────────────
  {
    id: 'browser-chrome',
    name: 'Chrome Browser',
    category: 'browsers',
    description: 'Chrome-style browser frame with address bar and tabs',
    previewBg: '#0a0a0a',
    aspectRatio: '16/10',
    clipZone: { x: 0, y: 12, width: 100, height: 88 },
  },
  {
    id: 'browser-safari',
    name: 'Safari Browser',
    category: 'browsers',
    description: 'macOS Safari-style browser with rounded corners',
    previewBg: '#0f0f0f',
    aspectRatio: '16/10',
    clipZone: { x: 0, y: 10, width: 100, height: 90 },
  },
  {
    id: 'browser-dark',
    name: 'Dark Minimal Browser',
    category: 'browsers',
    description: 'Sleek dark browser frame for dev tool showcases',
    previewBg: '#050505',
    aspectRatio: '16/10',
    clipZone: { x: 0, y: 10, width: 100, height: 90 },
  },
  // ── WEBSITES ───────────────────────────────────────────────────────
  {
    id: 'website-fullpage',
    name: 'Full Page Scroll',
    category: 'websites',
    description: 'Long scrollable website screenshot with subtle shadow',
    previewBg: '#0a0a14',
    aspectRatio: '9/16',
    clipZone: { x: 5, y: 5, width: 90, height: 90 },
  },
  {
    id: 'website-perspective',
    name: 'Perspective Tilt',
    category: 'websites',
    description: 'Website screenshot in dramatic 3D perspective tilt',
    previewBg: '#14000a',
    aspectRatio: '16/10',
    clipZone: { x: 5, y: 5, width: 90, height: 90 },
  },
  {
    id: 'website-floating',
    name: 'Floating Card',
    category: 'websites',
    description: 'Website screenshot floating on a blurred dark background',
    previewBg: '#000a14',
    aspectRatio: '16/10',
    clipZone: { x: 5, y: 5, width: 90, height: 90 },
  },
  // ── MULTI-DEVICE ───────────────────────────────────────────────────
  {
    id: 'multi-full-suite',
    name: 'Full Suite',
    category: 'multi-device',
    description: 'Phone + Tablet + Laptop + Desktop together in one scene',
    previewBg: '#000a1a',
    aspectRatio: '16/9',
    clipZone: { x: 25, y: 5, width: 50, height: 60 },
  },
  {
    id: 'multi-phone-laptop',
    name: 'Phone + Laptop',
    category: 'multi-device',
    description: 'Compact two-device mockup scene',
    previewBg: '#0a001a',
    aspectRatio: '16/9',
    clipZone: { x: 15, y: 5, width: 70, height: 70 },
  },
  {
    id: 'multi-tablet-laptop',
    name: 'Tablet + Laptop',
    category: 'multi-device',
    description: 'Tablet beside an open laptop for SaaS previews',
    previewBg: '#001a0a',
    aspectRatio: '16/9',
    clipZone: { x: 10, y: 5, width: 80, height: 65 },
  },
];

export function getTemplatesByCategory(category: MockupCategory): MockupTemplate[] {
  return TEMPLATES.filter((t) => t.category === category);
}

export function getTemplateById(id: string): MockupTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function getCategoryById(id: MockupCategory): CategoryInfo | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
